services:
      db:
        image: postgres
        environment:
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
        env_file:
          - .env

      web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/usr/src/app
        ports:
          - 8000:8000
        env_file:
          - .env
        depends_on:
          - db
        environment:
          DB_NAME: ${DB_NAME}
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
          DB_HOST: db
          DB_PORT: 5432
