version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    env_file:
      - .env
  web:
    build: .
    command: >
      bash -c "
        python3 manage.py migrate &&
        python3 manage.py collectstatic --no-input &&
        python3 manage.py superuser_create &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432